/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./public/models/castle/scene.gltf --shadows --transform 
Files: ./public/models/castle/scene.gltf [973.65KB] > scene-transformed.glb [653.9KB] (33%)
Author: BlackSpire (https://sketchfab.com/blackspire)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/castle-village-scene-675b3afce21a4acaa1140645a5206db3
Title: Castle village scene
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Castle(props) {
  const { nodes, materials } = useGLTF('/models/castle/scene-transformed.glb');  

  return (
    <group {...props} scale={0.01} position={[-10,0.01,57]} rotation={[0,Math.PI,0]} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pCube806_lambert71_0.geometry} material={materials.PaletteMaterial001} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2204_Bordo_Zolla_01_Mat_0.geometry} material={materials.Bordo_Zolla_01_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2204_Erba_01_TileMat_0.geometry} material={materials.Erba_01_TileMat} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2216_Bordo_Zolla_02_Mat_0.geometry} material={materials.Bordo_Zolla_02_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.pCube1232_Mura_03_TileMat_0.geometry} material={materials.Mura_03_TileMat} />
      <mesh castShadow receiveShadow geometry={nodes.pCube1232_Casa_01_Mat_0.geometry} material={materials.PaletteMaterial002} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface848_Mura_01_TileMat_0.geometry} material={materials.Mura_01_TileMat} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface848_Passerella_Legno_TopMura_TileMura_0.geometry} material={materials.Passerella_Legno_TopMura_TileMura} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6399_Terreno_TileMat_3_0.geometry} material={materials.Terreno_TileMat_3} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6400_Terreno_TileMat_1_0.geometry} material={materials.Terreno_TileMat_1} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6402_Terreno_TileMat_2_0.geometry} material={materials.Terreno_TileMat_2} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6412_Terreno_TileMat_4_0.geometry} material={materials.Terreno_TileMat_4} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6403_Terreno_TileMat_7_0.geometry} material={materials.Terreno_TileMat_7} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6404_Terreno_TileMat_8_0.geometry} material={materials.Terreno_TileMat_8} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6405_Terreno_TileMat_9_0.geometry} material={materials.Terreno_TileMat_9} />
      <mesh castShadow receiveShadow geometry={nodes.pCube6496_Passerella_Legno_TopMura_02_Mat_0.geometry} material={materials.Passerella_Legno_TopMura_02_Mat} />
    </group>
  )
}

useGLTF.preload('/models/castle/scene-transformed.glb')
