/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./public/models/enemy/scene.gltf --shadows --transform 
Files: ./public/models/enemy/scene.gltf [182.97KB] > scene-transformed.glb [337.32KB] (-84%)
Author: Merto (https://sketchfab.com/minibotgraphics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-soldier-10081d39f6a340509ece409073a9213f
Title: Medieval Soldier
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function EnemyModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/enemy/scene-transformed.glb')
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Take 001"].play();
  }, []);
  return (
    <group ref={group} {...props} scale={0.5} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_29} skeleton={nodes.Object_7.skeleton} scale={0.025} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Material_295} skeleton={nodes.Object_8.skeleton} scale={0.025} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_27} skeleton={nodes.Object_9.skeleton} scale={0.025} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material_28} skeleton={nodes.Object_10.skeleton} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/enemy/scene-transformed.glb')
