/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./public/models/knight/scene.gltf --shadows --transform 
Files: ./public/models/knight/scene.gltf [274.17KB] > scene-transformed.glb [165.47KB] (40%)
Author: guigodead (https://sketchfab.com/guigodead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dark-knight-4206f5ca17144cdfb8500b95fecd36e3
Title: Dark Knight
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Knight(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/knight/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if(actions) actions["Dark_Knight_Bones|Dark_Knight_Walk"].play();
  }, [actions]);

  return (
    <group scale={0.007} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_78.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_79.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_80.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_82.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_83.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_84.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/knight/scene-transformed.glb')
