/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./public/models/player/scene.gltf --shadows --transform -D 
Files: ./public/models/player/scene.gltf [359.76KB] > scene-transformed.glb [191.06KB] (47%)
Author: joaobaltieri (https://sketchfab.com/joaobaltieri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-simple-character-free-demo-animations-ffcb3490d35148a5951d3b32d1e5a7cb
Title: Mini Simple Character (Free Demo + Animations)
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function OtherPlayerModel({ position, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/player/scene-transformed.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Idle | Jump | Loose | Run | Walk
    actions["Idle"].play();
  }, []);

  return (
    <group ref={group} {...props} position={position} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_11.skeleton} scale={2.016} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_12.skeleton} scale={2.016} />
        <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_14.skeleton} scale={2.016} />
        <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_16.skeleton} scale={2.016} />
        <skinnedMesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_46.skeleton} scale={2.016} />
        <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_48.skeleton} scale={2.016} />
        <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_49.skeleton} scale={2.016} />
        <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_51.skeleton} scale={2.016} />
        <skinnedMesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_52.skeleton} scale={2.016} />
        <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_54.skeleton} scale={2.016} />
        <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_56.skeleton} scale={2.016} />
        <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_58.skeleton} scale={2.016} />
        <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_60.skeleton} scale={2.016} />
        <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_62.skeleton} scale={2.016} />
        <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.mini_simple_material_secondary} skeleton={nodes.Object_64.skeleton} scale={2.016} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/player/scene-transformed.glb');
