/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./public/models/reptile/scene.gltf --shadows --transform 
Files: ./public/models/reptile/scene.gltf [157.46KB] > scene-transformed.glb [647.5KB] (-311%)
Author: Merto (https://sketchfab.com/minibotgraphics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-reptile-soldier-walking-with-sword-34e930c31dc74ff0ad4ad8564e910b8c
Title: Medieval Reptile Soldier Walking With Sword
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Reptile(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/reptile/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions);
    actions["Take 001"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_29} skeleton={nodes.Object_7.skeleton} rotation={[0, 0, -0.135]} scale={0.015} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/reptile/scene-transformed.glb')
